config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :operators
  resources :delivers
  resources :checkingins
  resources :pickups
  resources :drivers
  resources :orders, except: 'orders'
  resources :customers, except: 'customers#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'signup', to: 'customers#new'

 # static page routes
  get 'aboutus', to: 'pages#aboutus'
  get 'contactus', to: 'pages#contactus'
  get 'faq', to: 'pages#faqpage'

  # User Session Stuff
  get 'user/login', to: 'sessions#new'
  post 'user/login', to:'sessions#create'
  delete 'user/logout', to: 'sessions#destroy'

  # Driver Stuff
  get 'driver_management_page', to: 'drivers#driver_main_page'

  # Customer Stuff
  get 'main_page', to: 'customers#main_page'

  # Operator Stuff
  get 'operator_management_page', to: 'operators#operator_main_page'
  get 'new_orders_page', to: 'operators#new_orders_page'
  get 'in_progress_orders_page', to: 'operators#in_progress_orders_page'
  get 'unpaid_orders_page', to: 'operators#unpaid_orders_page'
  get 'complete_orders_page', to: 'operators#complete_orders_page'

  get 'process_payment', to: 'payments#new'


end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  validates :first_name, presence: true, length: {minimum: 2}, format: { with: /\A[a-zA-Z]+\z/, message: "your first name must only contain letters" }
  validates :last_name, presence: true, length: {minimum: 2}, format: { with: /\A[a-zA-Z]+\z/, message: "your last name must only contain letters" }
  validates :card_no, presence: true, numericality: true, length: {minimum: 15, maximum: 16} # Amex has 15 digits and Mastercard and Visa have 16 digits
  validates :card_type, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "your card type must only contain letters" }
  validates :ccv, presence: true, numericality: true, length: {minimum: 3, maximum: 3}
  validates :card_expiry, presence: true
  validates :street, presence: true
  validates :suburb, presence: true, format: { with: /\A[a-zA-Z ]+\z/, message: "your suburb must only contain letters" }
  validates :postcode, presence: true, length: {minimum: 4, maximum: 4}
  validates :city, presence: true, format: { with: /\A[a-zA-Z ]+\z/, message: "your city must only contain letters" }
  validates :email, presence: true, length: {maximum: 100}, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  validates :password_digest, presence: true, length: {minimum: 8}

  has_secure_password
end

app/controllers/customers_controller.rb
# Customers Controller
#
# Contains helper methods and code-behind for 'customer' objects
# and their corresponding views and model

class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:success] = "Customer account successfully created"
      redirect_to user_login_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update

  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:username, :first_name, :last_name, :card_no, :card_type, :ccv, :card_expiry, :street, :suburb, :postcode, :city, :email, :password)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= render("shared/errors", obj: @customer) %>
<%= form_for(customer, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <label for="username" class="col-sm-4 control-label">Username</label>
      <div class="col-sm-6">
        <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
      </div>
    </div>

    <div class="form-group">
      <label for="username" class="col-sm-4 control-label">First Name</label>
      <div class="col-sm-6">
        <%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
      </div>
    </div>

    <div class="form-group">
      <label for="username" class="col-sm-4 control-label">Last Name</label>
      <div class="col-sm-6">
        <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
      </div>
    </div>

    <div class="form-group">
      <label for="card_no" class="col-sm-4 control-label">Card Number</label>
      <div class="col-sm-6">
        <%= f.text_field :card_no, class: "form-control", placeholder: "Card Number" %>
      </div>
    </div>

    <div class="row" id="offset">
      <div class="col-sm-6">
        <div class="radio-inline">
          <label>
            <%= f.radio_button(:card_type, "Visa", class: "") %>
            <%= label_tag(:card_type, "Visa", class: "radiobutton") %>
          </label>
        </div>
        <div class="radio-inline">
          <label>
            <%= f.radio_button(:card_type, "Mastercard", class: "") %>
            <%= label_tag(:card_type, "Mastercard", class: "radiobutton") %>
          </label>
        </div>
      </div>

    </div>

    <div class="form-group">
      <label for="ccv" class="col-sm-4 control-label">CCV</label>
      <div class="col-sm-6">
        <%= f.text_field :ccv, class: "form-control", placeholder: "CCV" %>
      </div>
    </div>

    <div class="form-group">
      <label for="card_no" class="col-sm-4 control-label">Card Expiry Date</label>
      <div class="col-sm-6">
        <%= f.text_field :card_expiry, :readonly => true, class: "form-control", placeholder: "Card Expiry Date", :data => {:provide => "datepicker", :"date-format" => "mm-yy", :"date-days-of-week-disabled" => "enabled", :"date-view-mode" => "months", :"date-min-view-mode" => "months"} %>
      </div>
    </div>

    <div class="form-group">
      <label for="card_no" class="col-sm-4 control-label">Street</label>
      <div class="col-sm-6">
        <%= f.text_field :street, class: "form-control", placeholder: "Street" %>
      </div>
    </div>

    <div class="form-group">
      <label for="card_no" class="col-sm-4 control-label">Suburb</label>
      <div class="col-sm-6">
        <%= f.text_field :suburb, class: "form-control", placeholder: "Suburb" %>
      </div>
    </div>

    <div class="form-group">
      <label for="card_no" class="col-sm-4 control-label">Post Code</label>
      <div class="col-sm-6">
        <%= f.text_field :postcode, class: "form-control", placeholder: "Post Code" %>
      </div>
    </div>

    <div class="form-group">
      <label for="card_no" class="col-sm-4 control-label">City</label>
      <div class="col-sm-6">
        <%= f.text_field :city, class: "form-control", placeholder: "City" %>
      </div>
    </div>


    <div class="form-group">
      <label for="card_no" class="col-sm-4 control-label">Email Address</label>
      <div class="col-sm-6">
        <%= f.text_field :email, class: "form-control", placeholder: "Email Address" %>
      </div>
    </div>

    <div class="form-group">
      <label for="card_no" class="col-sm-4 control-label">Password</label>
      <div class="col-sm-6">
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
    </div>

    <%= f.submit class: "btn btn-primary button-float" %>

<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', main_page_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Card no</th>
      <th>Card type</th>
      <th>Ccv</th>
      <th>Card expiry</th>
      <th>Street</th>
      <th>Suburb</th>
      <th>Postcode</th>
      <th>City</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.username %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.card_no %></td>
        <td><%= customer.card_type %></td>
        <td><%= customer.ccv %></td>
        <td><%= customer.card_expiry %></td>
        <td><%= customer.street %></td>
        <td><%= customer.suburb %></td>
        <td><%= customer.postcode %></td>
        <td><%= customer.city %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/main_page.html.erb
<%= require_customer %>

<p id="notice"><%= notice %></p>

<%= render('layouts/customer_sidebar') %>

</div>

app/views/customers/new.html.erb
<div class="main-include-margin">
  <div class="form-container">
    <div class="panel panel-default">
      <div class="panel-heading text-center">Customer Sign Up</div>
      <div class="panel-body">
        <%= render 'form', customer: @customer %>
      </div>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @customer.username %>
</p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Card no:</strong>
  <%= @customer.card_no %>
</p>

<p>
  <strong>Card type:</strong>
  <%= @customer.card_type %>
</p>

<p>
  <strong>Ccv:</strong>
  <%= @customer.ccv %>
</p>

<p>
  <strong>Card expiry:</strong>
  <%= @customer.card_expiry %>
</p>

<p>
  <strong>Street:</strong>
  <%= @customer.street %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @customer.suburb %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @customer.postcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', main_page_path %>