config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :operators
  resources :delivers
  resources :checkingins
  resources :pickups
  resources :drivers
  resources :orders, except: 'orders'
  resources :customers, except: 'customers#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'signup', to: 'customers#new'

 # static page routes
  get 'aboutus', to: 'pages#aboutus'
  get 'contactus', to: 'pages#contactus'
  get 'faq', to: 'pages#faqpage'

  # User Session Stuff
  get 'user/login', to: 'sessions#new'
  post 'user/login', to:'sessions#create'
  delete 'user/logout', to: 'sessions#destroy'

  # Driver Stuff
  get 'driver_management_page', to: 'drivers#driver_main_page'

  # Customer Stuff
  get 'main_page', to: 'customers#main_page'

  # Operator Stuff
  get 'operator_management_page', to: 'operators#operator_main_page'
  get 'new_orders_page', to: 'operators#new_orders_page'
  get 'in_progress_orders_page', to: 'operators#in_progress_orders_page'
  get 'unpaid_orders_page', to: 'operators#unpaid_orders_page'
  get 'complete_orders_page', to: 'operators#complete_orders_page'

  get 'process_payment', to: 'payments#new'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkingin.rb
class Checkingin < ApplicationRecord
  validates :order_id, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  validates :first_name, presence: true, length: {minimum: 2}, format: { with: /\A[a-zA-Z]+\z/, message: "your first name must only contain letters" }
  validates :last_name, presence: true, length: {minimum: 2}, format: { with: /\A[a-zA-Z]+\z/, message: "your last name must only contain letters" }
  validates :card_no, presence: true, numericality: true, length: {minimum: 15, maximum: 16} # Amex has 15 digits and Mastercard and Visa have 16 digits
  validates :card_type, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "your card type must only contain letters" }
  validates :ccv, presence: true, numericality: true, length: {minimum: 3, maximum: 3}
  validates :card_expiry, presence: true
  validates :street, presence: true
  validates :suburb, presence: true, format: { with: /\A[a-zA-Z ]+\z/, message: "your suburb must only contain letters" }
  validates :postcode, presence: true, length: {minimum: 4, maximum: 4}
  validates :city, presence: true, format: { with: /\A[a-zA-Z ]+\z/, message: "your city must only contain letters" }
  validates :email, presence: true, length: {maximum: 100}, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  validates :password_digest, presence: true, length: {minimum: 8}

  has_secure_password
end

app/models/deliver.rb
class Deliver < ApplicationRecord
  validates :order_id, presence: true
end

app/models/driver.rb
class Driver < ApplicationRecord

  VALID_NUMBER_PLATE_REGEX =  /[0-9]{1,3}[A-Z]{1,3}/
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :company_email, presence: true, length: {maximum: 100}, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  validates :first_name, presence: true, length: {minimum: 2}
  validates :last_name, presence: true, length: {minimum: 2}
  validates :assigned_truck_rego, presence: true, length:{minimum: 6, maximum: 6}, uniqueness: true, format: {with: VALID_NUMBER_PLATE_REGEX}
  validates :password_digest, presence: true, length: {minimum: 8}


  has_secure_password

end

app/models/operator.rb
class Operator < ApplicationRecord
  VALID_NUMBER_PLATE_REGEX =  /[0-9]{1,3}[A-Z]{1,3}/

  validates :company_email, presence: true, uniqueness: {case_sensitive: false}
  validates :first_name, presence: true, length: {minimum: 2}, format: { with: /\A[a-zA-Z]+\z/, message: "your first name must only contain letters" }
  validates :last_name, presence: true, length: {minimum: 2}, format: { with: /\A[a-zA-Z]+\z/, message: "your last name must only contain letters" }

  has_secure_password
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :customer, :dependent => :destroy

  # User id is injected afterwards, as the currently logged in user places the order and the id is sourced from that
  # not user input
  #validates :user_id, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  VALID_TIME_REGEX = /\A([01]?[0-9]|2[0-3])\:[0-5][0-9]\z/
  validates :pickup_time, presence: true, format: {with: VALID_TIME_REGEX}
  validates :no_packages, presence: true, numericality: true
  validates :gross_weight, presence: true, numericality: true
  validates :receiver_name, presence: true, length: {minimum: 2}, format: { with: /\A[a-zA-Z ]+\z/, message: "your name must only contain letters" }
  validates :receiver_street, presence: true
  validates :receiver_suburb, presence: true, format: { with: /\A[a-zA-Z ]+\z/, message: "your suburb must contain letters only" }
  validates :receiver_city, presence: true, format: { with: /\A[a-zA-Z ]+\z/, message: "your city must contain letters only" }
  validates :receiver_postcode, presence: true, numericality: true, length: {minimum: 4, maximum: 4}
  validates :insurance, presence: true

end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pickup.rb
class Pickup < ApplicationRecord
  validates :order_id, presence: true, format: { without: /\A0\z/, message: "must select an order" }
  validates :charge, presence: true, numericality: true
  validates :signature, presence: true
end

app/controllers/orders_controller.rb
# Orders Controller
#
# Contains helper methods and code-behind for 'order' objects
# and their corresponding views and model

class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.customer_id = session[:user_id]

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order }
        flash[:success] = "Your order has been submitted"
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :no_packages, :gross_weight, :pickup_time, :created_at, :updated_at, :receiver_name, :receiver_street, :receiver_suburb, :receiver_city, :receiver_postcode, :insurance)
    end
end

app/controllers/pages_controller.rb
# Pages Controller
#
# Empty Pages controller, no helper methods required for static pages

class PagesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkingins_helper.rb
module CheckinginsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/delivers_helper.rb
module DeliversHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/views/driver_sessions/_loginform.html.erb
<div class="form-container">
  <div class="panel panel-default">
    <div class="panel-heading text-center">Driver Log In</div>
      <div class="panel-body">
        <%= form_for(:session, url: driver_login_path) do |f| %>
          <div class="form-group">
            <%= f.label :company_email %>
            <%= f.email_field :company_email, class: "form-control", placeholder: "Enter Email" %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control", autocomplete: "off", placeholder: "Enter Password" %>
          </div>
          <%= f.submit "Log in", class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
</div>

app/views/layouts/_awaitingchargeorderstatepartial.html.erb
<!--order status partial-->


<div class="panel panel-default order-state">
  <div class="panel-heading" style="overflow: auto;">
    <h4 class="panel-title">
      <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#<%= collapse %>">

        <div class="status-title" style="width: 50%; float: left;">
          Order ID: <%= id %> Date Placed: <%= time %>
        </div>

        <div style="float: right;">
          <%= link_to "Process Payment", process_payment_path(:user_id => customer_id, :order_id => id, :charge => amount_to_charge) %>
        </div>

      </a>
    </h4>
  </div>
  <div id="<%= collapse %>" class="panel-collapse collapse">
    <div class="panel-body">
      <table class="status-table">

        <tr>
          <td>Amount to Charge: </td>
          <td><%= amount_to_charge %></td>
        </tr>
        <tr>
          <td>Name of Customer to be charged: </td>
          <td> <%= sender_name_var %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<!--partial end-->

app/views/layouts/_completeorderstatepartial.html.erb
<!--order status partial-->


<div class="panel panel-default order-state">
  <div class="panel-heading" style="overflow: auto;">
    <h4 class="panel-title">
      <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#<%= collapse %>">

        <div class="status-title" style="width: 50%; float: left;">
          Order ID: <%= id %>
        </div>

        <div style="float: right;">
          <%= amount_to_charge %>
        </div>

      </a>
    </h4>
  </div>
  <div id="<%= collapse %>" class="panel-collapse collapse">
    <div class="panel-body">
      <table class="status-table">

        <tr>
          <td>Order Placed On: </td>
          <td><%= time_ordered %></td>
        </tr>
        <tr>
          <td>Order Delivered On: </td>
          <td><%= time_delivered %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<!--partial end-->

app/views/layouts/_customer_sidebar.html.erb
<div class="left-menu">
  <h1>
    Customer Dashboard
  </h1>
  </br>
  <ul class="nav nav-links">
    <li><%= link_to("Place an Order", new_order_path ) %></li>
  </ul>

</div>

app/views/layouts/_driver_sidebar.html.erb
<div class="left-menu">
  <h1>
    Driver Dashboard
  </h1>
  </br>
  <ul class="nav nav-links">
    <li><%= link_to("Log Order Pickup", new_pickup_path ) %></li>
    <li><%= link_to("Log Warehouse Check in", new_checkingin_path ) %></li>
    <li><%= link_to("Log Order Delivery", new_deliver_path ) %></li>
  </ul>

</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; IFB299 - Package Delivery Service
    </small>
  </footer>
</div>

app/views/layouts/_inprogressorderstatepartial.html.erb
<!--order status partial-->
<!-- variables: o_id : order id number-->
<!-- variables: tracker : number of steps in process completed-->

<%  local_tracker = tracker %>

<div class="panel panel-default order-state">
  <div class="panel-heading" style="overflow: auto;">
    <h4 class="panel-title">
      <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#<%= collapse %>">

        <div class="status-title" style="width: 50%; float: left;">
          Order ID: <%= id %> Date Placed: <%= time %>
        </div>
        <div class="progress progress-format" style="margin: 0px; width: 50%; float: right;">
          <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"
               aria-valuenow="<%= percentage %>" aria-valuemin="0" aria-valuemax="100" style="width:<%= percentage %>%">
            <%= percentage %>%
          </div>
        </div>

      </a>
    </h4>
  </div>
  <div id="<%= collapse %>" class="panel-collapse collapse">
    <div class="panel-body">
      <table class="status-table">
        <tr class="header-row-order-status">
          <td>Current Order Status: </td>
          <td class="success"><%= status %></td>
        </tr>
        <% if local_tracker > 0 %>
            <tr>
              <td>Pickup Time: </td>
              <td>
                <div class="progress status-inner-progress-bar">
                  <div class="progress-bar progress-bar-danger progress-bar-striped active" role="progressbar"
                       aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:33%">
                    <%= pickup_time %>
                  </div>
                </div>
              </td>
            </tr>
            <% local_tracker -= 1 %>
        <% end %>

        <% if local_tracker > 0 %>
            <tr>
              <td>Check In Time: </td>
              <td>
                <div class="progress status-inner-progress-bar">
                  <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar"
                       aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:66%">
                    <%= checkin_time %>
                  </div>
                </div>
              </td>
            </tr>
            <% local_tracker -= 1 %>
        <% end %>

        <% if local_tracker > 0 %>
            <tr>
              <td>Delivery Time: </td>
              <td>
                <div class="progress status-inner-progress-bar">
                  <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"
                       aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
                    <%= deliver_time %>
                  </div>
                </div>
              </td>
            </tr>
            <% local_tracker -= 1 %>
        <% end %>
      </table>
    </div>
  </div>
</div>
<!--partial end-->

app/views/layouts/_messages.html.erb
<div style="padding: 20px; position: fixed; width: 90%;">
  <div class="row">
      <% flash.each do |name, msg| %>
          <div class='alert alert-<%="#{name} messages-fixed" %>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
          </div>
      <% end %>

  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="row">


  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to("On the Spot Couriers", root_path, class: "navbar-brand") %>

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'About Us', aboutus_path %></li>
          <li><%= link_to 'Contact Us', contactus_path %></li>
          <li><%= link_to 'FAQ', faq_path %></li>
          <% if customer_logged_in? %>
              <li><%= link_to 'Customer Management', main_page_path %></li>
          <% end %>
          <% if driver_logged_in? %>
              <li><%= link_to 'Driver Management', driver_management_page_path %></li>
          <% end %>
          <% if operator_logged_in? %>
              <li><%= link_to 'Operator Management', operator_management_page_path %></li>
          <% end %>
          <% if user_logged_in? %>
              <li><%= link_to 'Log Out', user_logout_path, method: :delete %></li>
          <% else %>
              <li><%= link_to 'Log In', user_login_path %></li>
              <li><%= link_to 'Sign Up', new_customer_path %></li>
          <% end %>

          <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Management <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu">-->
          <!--<li><a href="#">Driver Login</a></li>-->
          <!--<li><a href="#">Operator Login</a></li>-->
          <!--</ul>-->
          <!--</li>-->
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>

app/views/layouts/_neworderstatepartial.html.erb
<!--order status partial-->
<!-- variables: o_id : order id number-->
<!-- variables: tracker : number of steps in process completed-->

<div class="panel panel-default order-state">
  <div class="panel-heading" style="overflow: auto;">
    <h4 class="panel-title">
      <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#<%= collapse %>">

        <div class="status-title" style="width: 50%; float: left;">
          Order ID: <%= id %> Date Placed: <%= time %>
        </div>

      </a>
    </h4>
  </div>
  <div id="<%= collapse %>" class="panel-collapse collapse">
    <div class="panel-body">
      <table class="status-table">
        <tr class="header-row-order-status">
          <td>Current Order Status: </td>
          <td class="success"><%= status %></td>
        </tr>

        <tr>
          <td>Order Placed By: </td>
          <td><%= sender_name %></td>

        </tr>
        <tr>
          <td>Order Recipient:  </td>
          <td><%= recipient_name %></td>
        </tr>

      </table>
    </div>
  </div>
</div>
<!--partial end-->

app/views/layouts/_operator_sidebar.html.erb
<div class="left-menu">
  <h1>
    Operator Dashboard
  </h1>
  </br>
  <ul class="nav nav-links">
    <li><%= link_to("View New Orders", new_orders_page_path ) %></li>
    <li><%= link_to("Order Tracking Information", in_progress_orders_page_path ) %></li>
    <li><%= link_to("Orders Awaiting Charge", unpaid_orders_page_path ) %></li>
    <li><%= link_to("Complete Orders", complete_orders_page_path ) %></li>
    <li><%= link_to("Add Driver Account", new_driver_path ) %></li>
    <li><%= link_to("Add Operator Account", new_operator_path ) %></li>
  </ul>

</div>

app/views/layouts/_orderstate.html.erb
<!--order status partial-->
<!-- variables: o_id : order id number-->
<!-- variables: oall_percent : overall percentage value->-->

<div class="panel panel-default order-state">
  <div class="panel-heading" style="overflow: auto;">
    <h4 class="panel-title">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">

        <div class="status-title" style="width: 50%; float: left;">
          Order ID: 1 Total Time: 14 Hours
        </div>
        <div class="progress" style="margin: 0px; width: 50%; float: right;">
          <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"
               aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
            100%
          </div>
        </div>

      </a>
    </h4>
  </div>
  <div id="collapseOne" class="panel-collapse collapse in">
    <div class="panel-body">
      <table class="status-table">
        <tr class="header-row-order-status">
          <td>Current Order Status: </td>
          <td class="success">Completed</td>
          </td>
        <%= if tracker > 0 %>
          <tr>
            <td>Pickup Time: </td>
            <td>
              <div class="progress status-inner-progress-bar">
                <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"
                     aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:40%">
                  Total Time: 2 Hours
                </div>
              </div>
            </td>
          </tr>
            <% tracker-- %>
        <%= end %>

        <%= if tracker > 0 %>
          <tr>
            <td>Check In Time: </td>
            <td>
              <div class="progress status-inner-progress-bar">
                <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar"
                     aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:80%">
                  Total Time: 6 Hours
                </div>
              </div>
            </td>
          </tr>
            <% tracker-- %>
        <%= end %>

        <%= if tracker > 0 %>
        <tr>
          <td>Delivery Time: </td>
          <td>
            <div class="progress status-inner-progress-bar">
              <div class="progress-bar progress-bar-danger progress-bar-striped active" role="progressbar"
                   aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:90%">
                Total Time: 7 Hours
              </div>
            </div>
          </td>
        </tr>
        <% tracker-- %>
        <%= end %>

      </table>
    </div>
  </div>
</div>
<!--partial end-->

app/views/layouts/_sidebar.html.erb
<div class="left-menu">
  <h1>
    Customer Dashboard
  </h1>
  </br>
  <ul class="nav nav-pills nav-stacked center-links">
    <li><%= link_to("Place an Order", new_order_path ) %></li>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>On The Spot Couriers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

      <%= render('layouts/navigation') %>

        <div class="main">
          <%= render('layouts/messages') %>

          <%= yield %>
        </div>


  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited customer account creation:
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>

<% end %>