config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :operators
  resources :delivers
  resources :checkingins
  resources :pickups
  resources :drivers
  resources :orders, except: 'orders'
  resources :customers, except: 'customers#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'signup', to: 'customers#new'

 # static page routes
  get 'aboutus', to: 'pages#aboutus'
  get 'contactus', to: 'pages#contactus'
  get 'faq', to: 'pages#faqpage'

  # User Session Stuff
  get 'user/login', to: 'sessions#new'
  post 'user/login', to:'sessions#create'
  delete 'user/logout', to: 'sessions#destroy'

  # Driver Stuff
  get 'driver_management_page', to: 'drivers#driver_main_page'

  # Customer Stuff
  get 'main_page', to: 'customers#main_page'

  # Operator Stuff
  get 'operator_management_page', to: 'operators#operator_main_page'
  get 'new_orders_page', to: 'operators#new_orders_page'
  get 'in_progress_orders_page', to: 'operators#in_progress_orders_page'
  get 'unpaid_orders_page', to: 'operators#unpaid_orders_page'
  get 'complete_orders_page', to: 'operators#complete_orders_page'

  get 'process_payment', to: 'payments#new'


end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/payments_controller.rb
# Payments Controller
#
# Contains helper methods and code-behind for 'payment' objects
# and their corresponding views and model

class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @customer_id = params[:user_id]
    @order_pass_id = params[:order_id]
    @info = fetch_payment_information
    @charge = params[:charge]
    @names_array = fetch_payment_labels
  end

  def fetch_payment_information
    info = Array.new
    customer = Customer.find(params[:user_id])

    # 2, 3, 4, 5, 6, 7

    # add values
    if customer != nil
      info << customer[:first_name]
      info << customer[:last_name]
      info << customer[:card_no]
      info << customer[:card_type]
      info << customer[:ccv]
      info << customer[:card_expiry]
    else
      return "ERROR"
    end

    return info
  end

  def fetch_payment_labels
    return ["First Name", "Last Name", "Card Number", "Card Type", "CCV", "Card Expiry"]
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.paid = "Yes"
    respond_to do |format|
      if @payment.save
        flash[:success] = "Payment Process Complete"
        format.html { redirect_to @payment }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:order_id, :paid, :user_id, :order_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= render("shared/errors", obj: @payment) %>
<%= form_for(payment, :html => {role: "form"}) do |f| %>

    <label>Customer Payment Information: </label>
    <table class="payment-info-table">
      <tr><td><b>Amount to charge:</b></td><td><%= @charge %></td></tr>
      <% counter = 0 %>
      <% @info.each do |item| %>
          <tr>
          <td><b><%= @names_array[counter] %>:</b></td>
          <td><%= item %></td>
          </tr>
          <% counter += 1 %>

      <% end %>
    </table>

    </br>


    <div class="form-group">
      <%= f.label :order_id %>
      <%= f.text_field :order_id, class: "form-control", :value => @order_pass_id, :readonly => true %>
    </div>

    <div class="form-group">
      <%= f.submit "Click to Mark as 'Paid'", class: "btn btn-primary float-right" %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.order_id %></td>
        <td><%= payment.paid %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<%= require_operator %>

<p id="notice"><%= notice %></p>

<%= render('layouts/operator_sidebar') %>
<div class="left-menu-space"></div>

<div class="right-content form-right">

  <!-- New Orders -->

  <div class="sub-heading">
    <h1>Process Payment</h1>
    <hr>
    <p>The Order below has yet to be charged for</p>
  </div>
  <%= render 'form', payment: @payment %>

</div>

app/views/payments/show.html.erb
<%= require_operator %>

<p id="notice"><%= notice %></p>

<%= render('layouts/operator_sidebar') %>
<div class="left-menu-space"></div>

<div class="right-content form-right">
  <div class="sub-heading">
    <h1>Payment Complete</h1>
    <hr>
  </div>

  <p>
    <strong>Order:</strong>
    <%= @payment.order_id %>
  </p>

  <p>
    <strong>Paid:</strong>
    <%= @payment.paid %>
  </p>

</div>