config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :operators
  resources :delivers
  resources :checkingins
  resources :pickups
  resources :drivers
  resources :orders, except: 'orders'
  resources :customers, except: 'customers#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'signup', to: 'customers#new'

 # static page routes
  get 'aboutus', to: 'pages#aboutus'
  get 'contactus', to: 'pages#contactus'
  get 'faq', to: 'pages#faqpage'

  # User Session Stuff
  get 'user/login', to: 'sessions#new'
  post 'user/login', to:'sessions#create'
  delete 'user/logout', to: 'sessions#destroy'

  # Driver Stuff
  get 'driver_management_page', to: 'drivers#driver_main_page'

  # Customer Stuff
  get 'main_page', to: 'customers#main_page'

  # Operator Stuff
  get 'operator_management_page', to: 'operators#operator_main_page'
  get 'new_orders_page', to: 'operators#new_orders_page'
  get 'in_progress_orders_page', to: 'operators#in_progress_orders_page'
  get 'unpaid_orders_page', to: 'operators#unpaid_orders_page'
  get 'complete_orders_page', to: 'operators#complete_orders_page'

  get 'process_payment', to: 'payments#new'


end

app/models/driver.rb
class Driver < ApplicationRecord

  VALID_NUMBER_PLATE_REGEX =  /[0-9]{1,3}[A-Z]{1,3}/
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :company_email, presence: true, length: {maximum: 100}, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  validates :first_name, presence: true, length: {minimum: 2}
  validates :last_name, presence: true, length: {minimum: 2}
  validates :assigned_truck_rego, presence: true, length:{minimum: 6, maximum: 6}, uniqueness: true, format: {with: VALID_NUMBER_PLATE_REGEX}
  validates :password_digest, presence: true, length: {minimum: 8}


  has_secure_password

end

app/controllers/drivers_controller.rb
# Driver Controller
#
# Contains helper methods and code-behind for 'driver' objects
# and their corresponding views and model

class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  def driver_main_page
    @names = Customer.where(:id => Order.select("customer_id"))
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    temp = driver_params[:company_email]
    @driver = Driver.new(driver_params)
    @driver.company_email = temp.concat("@driver.onthespot.com.au")
    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver }
        flash[:success] = "Driver Account has been submitted"
        format.json { render :show, status: :created, location: @driver }
      else
        @driver.company_email = ""
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def return_customers_table
    @customers = Customer.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:first_name, :last_name, :company_email, :assigned_truck_rego, :password)
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= render("shared/errors", obj: @driver) %>
<%= form_for(driver, :html => {role: "form"}) do |f| %>

    <div class="form-group">
      <label for="company_email">Company Username</label>
        <%= f.text_field :company_email, class: "form-control", placeholder: "left part of your company email" %>
    </div>

    <div class="form-group">
      <label for="first_name">First Name</label>
        <%= f.text_field :first_name, class: "form-control", placeholder: "John" %>
    </div>

    <div class="form-group">
      <label for="last_name">Last Name</label>
        <%= f.text_field :last_name, class: "form-control", placeholder: "Doe" %>
    </div>

    <div class="form-group">
      <label for="assigned_truck_rego">Assigned Truck Rego</label>
        <%= f.text_field :assigned_truck_rego, class: "form-control", placeholder: "195JDA" %>
    </div>

    <div class="form-group">
      <label for="password">Password</label>
        <%= f.password_field :password, class: "form-control", placeholder: "Picked By Driver" %>
    </div>


    <%= f.submit class: "btn btn-primary button-float" %>

<% end %>

app/views/drivers/driver_main_page.html.erb
<%= require_driver %>

<p id="notice"><%= notice %></p>

<%= render('layouts/driver_sidebar') %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Company email</th>
      <th>Assigned truck rego</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.first_name %></td>
        <td><%= driver.last_name %></td>
        <td><%= driver.company_email %></td>
        <td><%= driver.assigned_truck_rego %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<%= require_operator %>

<p id="notice"><%= notice %></p>

<%= render('layouts/operator_sidebar') %>
<div class="left-menu-space"></div>

<div class="right-content form-right">
  <div class="sub-heading">
    <h1>Create Driver Account</h1>
    <hr>
    <p>Add Driver record to the system</p>
  </div>

  <!-- New Orders -->

  <%= render 'form', driver: @driver %>


</div>

app/views/drivers/show.html.erb
<%= require_operator %>

<p id="notice"><%= notice %></p>

<%= render('layouts/operator_sidebar') %>
<div class="left-menu-space"></div>

<div class="right-content form-right">
  <div class="sub-heading">
    <h1>Driver Account Created</h1>
    <hr>
    <p>Summary of the driver record created</p>
  </div>


  <p>
    <strong>First name:</strong>
    <%= @driver.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @driver.last_name %>
  </p>

  <p>
    <strong>Company email:</strong>
    <%= @driver.company_email %>
  </p>

  <p>
    <strong>Assigned truck rego:</strong>
    <%= @driver.assigned_truck_rego %>
  </p>
</div>